object EditorView: TEditorView
  Left = 590
  Top = 268
  AlphaBlendValue = 128
  BorderIcons = []
  BorderStyle = bsSingle
  ClientHeight = 392
  ClientWidth = 624
  Color = clBtnFace
  UseDockManager = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  ShowHint = True
  OnShortCut = FormShortCut
  PixelsPerInch = 96
  TextHeight = 13
end
