program DDuce.Demos;

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  Vcl.SysStyles,
  MidasLib,
  Demo.Contact in 'Demo.Contact.pas',
  Demo.Data in 'Demo.Data.pas' {dmData: TDataModule},
  Demo.DDuce.DBGridView in 'Demo.DDuce.DBGridView.pas' {frmDBGridView},
  Demo.DDuce.DynamicRecord in 'Demo.DDuce.DynamicRecord.pas' {frmDynamicRecords},
  Demo.DDuce.PropertyInspector in 'Demo.DDuce.PropertyInspector.pas' {frmPropertyInspector},
  Demo.DDuce.Reflect in 'Demo.DDuce.Reflect.pas' {frmReflect},
  Demo.DDuce.ScopedReference in 'Demo.DDuce.ScopedReference.pas' {frmScopedReferences},
  Demo.DDuce.XMLTree in 'Demo.DDuce.XMLTree.pas' {frmXMLTree},
  Demo.Factories in 'Demo.Factories.pas',
  Demo.MainForm in 'Demo.MainForm.pas' {frmMainMenu},
  Demo.Manager in 'Demo.Manager.pas',
  Demo.Registration in 'Demo.Registration.pas',
  Demo.Utils in 'Demo.Utils.pas',
  Demo.DDuce.Logger in 'Demo.DDuce.Logger.pas' {frmLogger},
  Demo.DDuce.Inspector in 'Demo.DDuce.Inspector.pas' {frmInspector},
  Demo.DDuce.GridView in 'Demo.DDuce.GridView.pas' {frmGridView},
  DDuce.DynamicRecord in '..\Source\DDuce.DynamicRecord.pas',
  DDuce.RandomData in '..\Source\DDuce.RandomData.pas',
  DDuce.Reflect in '..\Source\DDuce.Reflect.pas',
  DDuce.ScopedReference in '..\Source\DDuce.ScopedReference.pas',
  DDuce.Components.DBGridView in '..\Source\Components\DDuce.Components.DBGridView.pas',
  DDuce.Components.GridView in '..\Source\Components\DDuce.Components.GridView.pas',
  DDuce.Components.Inspector in '..\Source\Components\DDuce.Components.Inspector.pas',
  DDuce.Components.LogTree in '..\Source\Components\DDuce.Components.LogTree.pas',
  DDuce.Components.PropertyInspector.CollectionEditor in '..\Source\Components\DDuce.Components.PropertyInspector.CollectionEditor.pas' {frmCollectionEditor},
  DDuce.Components.PropertyInspector in '..\Source\Components\DDuce.Components.PropertyInspector.pas',
  DDuce.Components.PropertyInspector.StringsEditor in '..\Source\Components\DDuce.Components.PropertyInspector.StringsEditor.pas' {StringsEditorDialog},
  DDuce.Components.XMLTree.Editors in '..\Source\Components\DDuce.Components.XMLTree.Editors.pas',
  DDuce.Components.XMLTree.NodeAttributes in '..\Source\Components\DDuce.Components.XMLTree.NodeAttributes.pas',
  DDuce.Components.XMLTree in '..\Source\Components\DDuce.Components.XMLTree.pas',
  DSharp.Bindings.Collections in '..\Source\Dependencies\DSharp\DSharp.Bindings.Collections.pas',
  DSharp.Bindings.CollectionView in '..\Source\Dependencies\DSharp\DSharp.Bindings.CollectionView.pas',
  DSharp.Bindings.Notifications in '..\Source\Dependencies\DSharp\DSharp.Bindings.Notifications.pas',
  DSharp.Collections.ObservableCollection in '..\Source\Dependencies\DSharp\DSharp.Collections.ObservableCollection.pas',
  DSharp.Core.Collections in '..\Source\Dependencies\DSharp\DSharp.Core.Collections.pas',
  DSharp.Core.DataTemplates.Default in '..\Source\Dependencies\DSharp\DSharp.Core.DataTemplates.Default.pas',
  DSharp.Core.DataTemplates in '..\Source\Dependencies\DSharp\DSharp.Core.DataTemplates.pas',
  DSharp.Core.DependencyProperty in '..\Source\Dependencies\DSharp\DSharp.Core.DependencyProperty.pas',
  DSharp.Core.Expressions in '..\Source\Dependencies\DSharp\DSharp.Core.Expressions.pas',
  DSharp.Core.Framework in '..\Source\Dependencies\DSharp\DSharp.Core.Framework.pas',
  DSharp.Core.PropertyChangedBase in '..\Source\Dependencies\DSharp\DSharp.Core.PropertyChangedBase.pas',
  DSharp.Core.Reflection in '..\Source\Dependencies\DSharp\DSharp.Core.Reflection.pas',
  DSharp.Core.Utils in '..\Source\Dependencies\DSharp\DSharp.Core.Utils.pas',
  DSharp.Windows.ColumnDefinitions.ControlTemplate in '..\Source\Dependencies\DSharp\DSharp.Windows.ColumnDefinitions.ControlTemplate.pas',
  DSharp.Windows.ColumnDefinitions in '..\Source\Dependencies\DSharp\DSharp.Windows.ColumnDefinitions.pas',
  DSharp.Windows.ControlTemplates in '..\Source\Dependencies\DSharp\DSharp.Windows.ControlTemplates.pas',
  DSharp.Windows.CustomPresenter in '..\Source\Dependencies\DSharp\DSharp.Windows.CustomPresenter.pas',
  DSharp.Windows.CustomPresenter.Types in '..\Source\Dependencies\DSharp\DSharp.Windows.CustomPresenter.Types.pas',
  DSharp.Windows.TreeViewPresenter in '..\Source\Dependencies\DSharp\DSharp.Windows.TreeViewPresenter.pas',
  NativeXml in '..\Source\Dependencies\NativeXml\NativeXml.pas',
  NativeXmlCodepages in '..\Source\Dependencies\NativeXml\NativeXmlCodepages.pas',
  NativeXmlNodes in '..\Source\Dependencies\NativeXml\NativeXmlNodes.pas',
  sdDebug in '..\Source\Dependencies\NativeXml\sdDebug.pas',
  sdStreams in '..\Source\Dependencies\NativeXml\sdStreams.pas',
  sdStringTable in '..\Source\Dependencies\NativeXml\sdStringTable.pas',
  DDuce.Logging.Appenders.LogTree in '..\Source\Logging\DDuce.Logging.Appenders.LogTree.pas',
  DDuce.Logging.Appenders.WinIPC in '..\Source\Logging\DDuce.Logging.Appenders.WinIPC.pas',
  DDuce.Components.Factories in '..\Source\Components\DDuce.Components.Factories.pas',
  Demo.DDuce.Editor in 'Demo.DDuce.Editor.pas' {frmEditor},
  DDuce.Editor.ActionList.Templates in '..\Source\Modules\Editor\DDuce.Editor.ActionList.Templates.pas',
  DDuce.Editor.ActionList.ToolView in '..\Source\Modules\Editor\DDuce.Editor.ActionList.ToolView.pas' {frmActionListView},
  DDuce.Editor.AlignLines.Settings in '..\Source\Modules\Editor\DDuce.Editor.AlignLines.Settings.pas',
  DDuce.Editor.CharacterMap.ToolView in '..\Source\Modules\Editor\DDuce.Editor.CharacterMap.ToolView.pas' {frmCharacterMap},
  DDuce.Editor.Codeformatters in '..\Source\Modules\Editor\DDuce.Editor.Codeformatters.pas',
  DDuce.Editor.Codeformatters.Sql in '..\Source\Modules\Editor\DDuce.Editor.Codeformatters.Sql.pas',
  DDuce.Editor.Codetags in '..\Source\Modules\Editor\DDuce.Editor.Codetags.pas',
  DDuce.Editor.Colors.Settings in '..\Source\Modules\Editor\DDuce.Editor.Colors.Settings.pas',
  DDuce.Editor.Commands in '..\Source\Modules\Editor\DDuce.Editor.Commands.pas',
  DDuce.Editor.Commentstripper in '..\Source\Modules\Editor\DDuce.Editor.Commentstripper.pas',
  DDuce.Editor.Events in '..\Source\Modules\Editor\DDuce.Editor.Events.pas',
  DDuce.Editor.Factories.Manager in '..\Source\Modules\Editor\DDuce.Editor.Factories.Manager.pas',
  DDuce.Editor.Factories.Menus in '..\Source\Modules\Editor\DDuce.Editor.Factories.Menus.pas',
  DDuce.Editor.Factories in '..\Source\Modules\Editor\DDuce.Editor.Factories.pas',
  DDuce.Editor.Factories.Settings in '..\Source\Modules\Editor\DDuce.Editor.Factories.Settings.pas',
  DDuce.Editor.Factories.Toolbars in '..\Source\Modules\Editor\DDuce.Editor.Factories.Toolbars.pas',
  DDuce.Editor.Factories.Views in '..\Source\Modules\Editor\DDuce.Editor.Factories.Views.pas',
  DDuce.Editor.Highlighters in '..\Source\Modules\Editor\DDuce.Editor.Highlighters.pas',
  DDuce.Editor.Interfaces in '..\Source\Modules\Editor\DDuce.Editor.Interfaces.pas',
  DDuce.Editor.Manager in '..\Source\Modules\Editor\DDuce.Editor.Manager.pas' {dmEditorManager: TDataModule},
  DDuce.Editor.Options.Settings in '..\Source\Modules\Editor\DDuce.Editor.Options.Settings.pas',
  DDuce.Editor.Resources in '..\Source\Modules\Editor\DDuce.Editor.Resources.pas' {ResourcesDataModule: TDataModule},
  DDuce.Editor.Search.Data in '..\Source\Modules\Editor\DDuce.Editor.Search.Data.pas',
  DDuce.Editor.Search.Engine in '..\Source\Modules\Editor\DDuce.Editor.Search.Engine.pas',
  DDuce.Editor.Search.Engine.Settings in '..\Source\Modules\Editor\DDuce.Editor.Search.Engine.Settings.pas',
  DDuce.Editor.Search.Templates in '..\Source\Modules\Editor\DDuce.Editor.Search.Templates.pas',
  DDuce.Editor.Search.Toolview in '..\Source\Modules\Editor\DDuce.Editor.Search.Toolview.pas' {frmSearchForm},
  DDuce.Editor.Selectioninfo.ToolView in '..\Source\Modules\Editor\DDuce.Editor.Selectioninfo.ToolView.pas',
  DDuce.Editor.Settings in '..\Source\Modules\Editor\DDuce.Editor.Settings.pas',
  DDuce.Editor.Sortstrings.Settings in '..\Source\Modules\Editor\DDuce.Editor.Sortstrings.Settings.pas',
  DDuce.Editor.Sortstrings.Toolview in '..\Source\Modules\Editor\DDuce.Editor.Sortstrings.Toolview.pas' {frmSortStrings},
  DDuce.Editor.Test.ToolView in '..\Source\Modules\Editor\DDuce.Editor.Test.ToolView.pas',
  DDuce.Editor.Tools.Settings in '..\Source\Modules\Editor\DDuce.Editor.Tools.Settings.pas',
  DDuce.Editor.ToolView.Base in '..\Source\Modules\Editor\DDuce.Editor.ToolView.Base.pas' {CustomEditorToolView},
  DDuce.Editor.ToolView.Manager in '..\Source\Modules\Editor\DDuce.Editor.ToolView.Manager.pas',
  DDuce.Editor.Types in '..\Source\Modules\Editor\DDuce.Editor.Types.pas',
  DDuce.Editor.Utils in '..\Source\Modules\Editor\DDuce.Editor.Utils.pas',
  DDuce.Editor.View in '..\Source\Modules\Editor\DDuce.Editor.View.pas' {EditorView},
  DDuce.Editor.Viewlist.Data in '..\Source\Modules\Editor\DDuce.Editor.Viewlist.Data.pas',
  DDuce.Editor.Viewlist.ToolView in '..\Source\Modules\Editor\DDuce.Editor.Viewlist.ToolView.pas' {frmViewList},
  DDuce.Editor.AlignLines.ToolView in '..\Source\Modules\Editor\DDuce.Editor.AlignLines.ToolView.pas' {frmAlignLines},
  DDuce.WinIPC.Client in '..\Source\DDuce.WinIPC.Client.pas',
  DDuce.WinIPC.Server in '..\Source\DDuce.WinIPC.Server.pas',
  ZeroMQ.API in '..\Source\Dependencies\ZeroMQ\ZeroMQ.API.pas',
  ZeroMQ in '..\Source\Dependencies\ZeroMQ\ZeroMQ.pas',
  DDuce.Editor.Filter.Data in '..\Source\Modules\Editor\DDuce.Editor.Filter.Data.pas',
  DDuce.Editor.Filter.Settings in '..\Source\Modules\Editor\DDuce.Editor.Filter.Settings.pas',
  DDuce.Editor.Filter.Toolview in '..\Source\Modules\Editor\DDuce.Editor.Filter.Toolview.pas' {frmFilter},
  DDuce.RTTEye in '..\Source\Modules\RTTEye\DDuce.RTTEye.pas' {frmRTTEye},
  DDuce.ObjectInspector.zObjectInspector in '..\Source\Modules\ObjectInspector\DDuce.ObjectInspector.zObjectInspector.pas' {frmComponentInspectorzObjectInspector},
  DDuce.Logger.Base in '..\Source\Modules\Logger\DDuce.Logger.Base.pas',
  DDuce.Logger.Channels.Base in '..\Source\Modules\Logger\DDuce.Logger.Channels.Base.pas',
  DDuce.Logger.Channels.LogFile in '..\Source\Modules\Logger\DDuce.Logger.Channels.LogFile.pas',
  DDuce.Logger.Channels.WinIPC in '..\Source\Modules\Logger\DDuce.Logger.Channels.WinIPC.pas',
  DDuce.Logger.Channels.WinODS in '..\Source\Modules\Logger\DDuce.Logger.Channels.WinODS.pas',
  DDuce.Logger.Channels.ZeroMQ in '..\Source\Modules\Logger\DDuce.Logger.Channels.ZeroMQ.pas',
  DDuce.Logger.Factories in '..\Source\Modules\Logger\DDuce.Logger.Factories.pas',
  DDuce.Logger.Interfaces in '..\Source\Modules\Logger\DDuce.Logger.Interfaces.pas',
  DDuce.Logger in '..\Source\Modules\Logger\DDuce.Logger.pas',
  DDuce.Utils in '..\Source\DDuce.Utils.pas',
  DDuce.Utils.WinApi in '..\Source\DDuce.Utils.WinApi.pas',
  Demo.Resources in 'Demo.Resources.pas',
  DDuce.Settings.Form in '..\Source\Settings\DDuce.Settings.Form.pas',
  DDuce.Settings.TextFormat in '..\Source\Settings\DDuce.Settings.TextFormat.pas',
  Demo.DDuce.VirtualTrees in 'Demo.DDuce.VirtualTrees.pas' {frmVirtualTrees},
  DDuce.Components.ValueList.Node in '..\Source\Components\DDuce.Components.ValueList.Node.pas',
  Demo.DDuce.ValueList in 'Demo.DDuce.ValueList.pas' {frmValueListDemo},
  DDuce.Components.ValueList in '..\Source\Components\DDuce.Components.ValueList.pas',
  DDuce.Factories.GridView in '..\Source\Factories\DDuce.Factories.GridView.pas',
  DDuce.Factories.LiveBindings in '..\Source\Factories\DDuce.Factories.LiveBindings.pas',
  DDuce.Factories.Toolbar in '..\Source\Factories\DDuce.Factories.Toolbar.pas',
  DDuce.Factories.TreeViewPresenter in '..\Source\Factories\DDuce.Factories.TreeViewPresenter.pas',
  DDuce.Factories.VirtualTrees in '..\Source\Factories\DDuce.Factories.VirtualTrees.pas',
  DDuce.Factories.zObjInspector in '..\Source\Factories\DDuce.Factories.zObjInspector.pas',
  zBase in '..\..\..\components\zcontrols\Source\zBase.pas',
  zCanvasStack in '..\..\..\components\zcontrols\Source\zCanvasStack.pas',
  zCollectionEditor in '..\..\..\components\zcontrols\Source\zCollectionEditor.pas' {zCollectionEditorDialog},
  zControlsReg in '..\..\..\components\zcontrols\Source\zControlsReg.pas',
  zGraphicDialog in '..\..\..\components\zcontrols\Source\zGraphicDialog.pas' {GraphicDialog},
  zObjInspDialogs in '..\..\..\components\zcontrols\Source\zObjInspDialogs.pas',
  zObjInspector in '..\..\..\components\zcontrols\Source\zObjInspector.pas',
  zObjInspList in '..\..\..\components\zcontrols\Source\zObjInspList.pas',
  zObjInspTypes in '..\..\..\components\zcontrols\Source\zObjInspTypes.pas',
  zRecList in '..\..\..\components\zcontrols\Source\zRecList.pas',
  zStringsDialog in '..\..\..\components\zcontrols\Source\zStringsDialog.pas' {StringsDialog},
  zUtils in '..\..\..\components\zcontrols\Source\zUtils.pas',
  zValueManager in '..\..\..\components\zcontrols\Source\zValueManager.pas',
  FloatConv.Double in '..\..\..\components\zcontrols\Source\FloatConv\FloatConv.Double.pas',
  FloatConv.Extended in '..\..\..\components\zcontrols\Source\FloatConv\FloatConv.Extended.pas',
  FloatConv in '..\..\..\components\zcontrols\Source\FloatConv\FloatConv.pas',
  FloatConv.Single in '..\..\..\components\zcontrols\Source\FloatConv\FloatConv.Single.pas',
  BCEditor.Consts in '..\..\..\components\TBCEditor\Source\BCEditor.Consts.pas',
  BCEditor.Editor.ActiveLine in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.ActiveLine.pas',
  BCEditor.Editor.Base in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Base.pas',
  BCEditor.Editor.Caret.MultiEdit.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Caret.MultiEdit.Colors.pas',
  BCEditor.Editor.Caret.MultiEdit in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Caret.MultiEdit.pas',
  BCEditor.Editor.Caret.NonBlinking.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Caret.NonBlinking.Colors.pas',
  BCEditor.Editor.Caret.NonBlinking in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Caret.NonBlinking.pas',
  BCEditor.Editor.Caret.Offsets in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Caret.Offsets.pas',
  BCEditor.Editor.Caret in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Caret.pas',
  BCEditor.Editor.Caret.Styles in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Caret.Styles.pas',
  BCEditor.Editor.CodeFolding.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.Colors.pas',
  BCEditor.Editor.CodeFolding.Hint.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Colors.pas',
  BCEditor.Editor.CodeFolding.Hint.Form in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Form.pas',
  BCEditor.Editor.CodeFolding.Hint.Indicator.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Indicator.Colors.pas',
  BCEditor.Editor.CodeFolding.Hint.Indicator in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.Indicator.pas',
  BCEditor.Editor.CodeFolding.Hint in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.Hint.pas',
  BCEditor.Editor.CodeFolding in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.pas',
  BCEditor.Editor.CodeFolding.Ranges in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.Ranges.pas',
  BCEditor.Editor.CodeFolding.Regions in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CodeFolding.Regions.pas',
  BCEditor.Editor.CompletionProposal.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Colors.pas',
  BCEditor.Editor.CompletionProposal.Columns.Items in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Columns.Items.pas',
  BCEditor.Editor.CompletionProposal.Columns in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Columns.pas',
  BCEditor.Editor.CompletionProposal.Columns.Title.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Columns.Title.Colors.pas',
  BCEditor.Editor.CompletionProposal.Columns.Title in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Columns.Title.pas',
  BCEditor.Editor.CompletionProposal in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CompletionProposal.pas',
  BCEditor.Editor.CompletionProposal.PopupWindow in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CompletionProposal.PopupWindow.pas',
  BCEditor.Editor.CompletionProposal.Trigger in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.CompletionProposal.Trigger.pas',
  BCEditor.Editor.DB in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.DB.pas',
  BCEditor.Editor.Directories in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Directories.pas',
  BCEditor.Editor.Glyph in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Glyph.pas',
  BCEditor.Editor.InternalImage in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.InternalImage.pas',
  BCEditor.Editor.KeyCommands in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.KeyCommands.pas',
  BCEditor.Editor.LeftMargin.Bookmarks in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.LeftMargin.Bookmarks.pas',
  BCEditor.Editor.LeftMargin.Border in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.LeftMargin.Border.pas',
  BCEditor.Editor.LeftMargin.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.LeftMargin.Colors.pas',
  BCEditor.Editor.LeftMargin.LineNumbers in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.LeftMargin.LineNumbers.pas',
  BCEditor.Editor.LeftMargin.LineState in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.LeftMargin.LineState.pas',
  BCEditor.Editor.LeftMargin.Marks in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.LeftMargin.Marks.pas',
  BCEditor.Editor.LeftMargin.MarksPanel in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.LeftMargin.MarksPanel.pas',
  BCEditor.Editor.LeftMargin in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.LeftMargin.pas',
  BCEditor.Editor.Marks in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Marks.pas',
  BCEditor.Editor.MatchingPair.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.MatchingPair.Colors.pas',
  BCEditor.Editor.MatchingPair in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.MatchingPair.pas',
  BCEditor.Editor.Minimap.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Minimap.Colors.pas',
  BCEditor.Editor.Minimap.Indicator in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Minimap.Indicator.pas',
  BCEditor.Editor.Minimap in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Minimap.pas',
  BCEditor.Editor.Minimap.Shadow in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Minimap.Shadow.pas',
  BCEditor.Editor in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.pas',
  BCEditor.Editor.PopupWindow in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.PopupWindow.pas',
  BCEditor.Editor.Replace in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Replace.pas',
  BCEditor.Editor.RightMargin.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.RightMargin.Colors.pas',
  BCEditor.Editor.RightMargin in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.RightMargin.pas',
  BCEditor.Editor.Scroll.Hint in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Scroll.Hint.pas',
  BCEditor.Editor.Scroll in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Scroll.pas',
  BCEditor.Editor.Scroll.Shadow in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Scroll.Shadow.pas',
  BCEditor.Editor.Search.Highlighter.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Search.Highlighter.Colors.pas',
  BCEditor.Editor.Search.Highlighter in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Search.Highlighter.pas',
  BCEditor.Editor.Search.InSelection in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Search.InSelection.pas',
  BCEditor.Editor.Search.Map.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Search.Map.Colors.pas',
  BCEditor.Editor.Search.Map in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Search.Map.pas',
  BCEditor.Editor.Search in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Search.pas',
  BCEditor.Editor.Selection.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Selection.Colors.pas',
  BCEditor.Editor.Selection in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Selection.pas',
  BCEditor.Editor.SkipRegions in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.SkipRegions.pas',
  BCEditor.Editor.SpecialChars.EndOfLine in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.SpecialChars.EndOfLine.pas',
  BCEditor.Editor.SpecialChars in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.SpecialChars.pas',
  BCEditor.Editor.SpecialChars.Selection in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.SpecialChars.Selection.pas',
  BCEditor.Editor.SyncEdit.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.SyncEdit.Colors.pas',
  BCEditor.Editor.SyncEdit in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.SyncEdit.pas',
  BCEditor.Editor.Tabs in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Tabs.pas',
  BCEditor.Editor.TokenInfo.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.TokenInfo.Colors.pas',
  BCEditor.Editor.TokenInfo in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.TokenInfo.pas',
  BCEditor.Editor.TokenInfo.PopupWindow in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.TokenInfo.PopupWindow.pas',
  BCEditor.Editor.TokenInfo.Title.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.TokenInfo.Title.Colors.pas',
  BCEditor.Editor.TokenInfo.Title in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.TokenInfo.Title.pas',
  BCEditor.Editor.Undo.Item in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Undo.Item.pas',
  BCEditor.Editor.Undo.List in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Undo.List.pas',
  BCEditor.Editor.Undo in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Undo.pas',
  BCEditor.Editor.UnknownChars in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.UnknownChars.pas',
  BCEditor.Editor.Utils in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.Utils.pas',
  BCEditor.Editor.WordWrap.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.WordWrap.Colors.pas',
  BCEditor.Editor.WordWrap in '..\..\..\components\TBCEditor\Source\BCEditor.Editor.WordWrap.pas',
  BCEditor.Encoding in '..\..\..\components\TBCEditor\Source\BCEditor.Encoding.pas',
  BCEditor.Export.HTML in '..\..\..\components\TBCEditor\Source\BCEditor.Export.HTML.pas',
  BCEditor.Highlighter.Attributes in '..\..\..\components\TBCEditor\Source\BCEditor.Highlighter.Attributes.pas',
  BCEditor.Highlighter.Colors in '..\..\..\components\TBCEditor\Source\BCEditor.Highlighter.Colors.pas',
  BCEditor.Highlighter.Comments in '..\..\..\components\TBCEditor\Source\BCEditor.Highlighter.Comments.pas',
  BCEditor.Highlighter.Import.JSON in '..\..\..\components\TBCEditor\Source\BCEditor.Highlighter.Import.JSON.pas',
  BCEditor.Highlighter.Info in '..\..\..\components\TBCEditor\Source\BCEditor.Highlighter.Info.pas',
  BCEditor.Highlighter in '..\..\..\components\TBCEditor\Source\BCEditor.Highlighter.pas',
  BCEditor.Highlighter.Rules in '..\..\..\components\TBCEditor\Source\BCEditor.Highlighter.Rules.pas',
  BCEditor.Highlighter.Token in '..\..\..\components\TBCEditor\Source\BCEditor.Highlighter.Token.pas',
  BCEditor.JsonDataObjects in '..\..\..\components\TBCEditor\Source\BCEditor.JsonDataObjects.pas',
  BCEditor.KeyboardHandler in '..\..\..\components\TBCEditor\Source\BCEditor.KeyboardHandler.pas',
  BCEditor.Language in '..\..\..\components\TBCEditor\Source\BCEditor.Language.pas',
  BCEditor.Lines in '..\..\..\components\TBCEditor\Source\BCEditor.Lines.pas',
  BCEditor.MacroRecorder in '..\..\..\components\TBCEditor\Source\BCEditor.MacroRecorder.pas',
  BCEditor.PaintHelper in '..\..\..\components\TBCEditor\Source\BCEditor.PaintHelper.pas',
  BCEditor.Print.HeaderFooter in '..\..\..\components\TBCEditor\Source\BCEditor.Print.HeaderFooter.pas',
  BCEditor.Print.Margins in '..\..\..\components\TBCEditor\Source\BCEditor.Print.Margins.pas',
  BCEditor.Print in '..\..\..\components\TBCEditor\Source\BCEditor.Print.pas',
  BCEditor.Print.Preview in '..\..\..\components\TBCEditor\Source\BCEditor.Print.Preview.pas',
  BCEditor.Print.PrinterInfo in '..\..\..\components\TBCEditor\Source\BCEditor.Print.PrinterInfo.pas',
  BCEditor.Print.Types in '..\..\..\components\TBCEditor\Source\BCEditor.Print.Types.pas',
  BCEditor.Search.Normal in '..\..\..\components\TBCEditor\Source\BCEditor.Search.Normal.pas',
  BCEditor.Search in '..\..\..\components\TBCEditor\Source\BCEditor.Search.pas',
  BCEditor.Search.RegularExpressions in '..\..\..\components\TBCEditor\Source\BCEditor.Search.RegularExpressions.pas',
  BCEditor.Search.Wildcard in '..\..\..\components\TBCEditor\Source\BCEditor.Search.Wildcard.pas',
  BCEditor.StyleHooks in '..\..\..\components\TBCEditor\Source\BCEditor.StyleHooks.pas',
  BCEditor.Types in '..\..\..\components\TBCEditor\Source\BCEditor.Types.pas',
  BCEditor.Utils in '..\..\..\components\TBCEditor\Source\BCEditor.Utils.pas';

{$R *.res}

begin
  {$WARNINGS OFF}
  ReportMemoryLeaksOnShutdown := DebugHook > 0;
  {$WARNINGS ON}
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  RegisterDemos;
  if DemoManager.ItemList.Count = 1 then
  begin
    DemoManager.Execute(DemoManager.ItemList.Single);
  end
  else
  begin
    Application.CreateForm(TfrmMainMenu, frmMainMenu);
  end;
  Application.Run;
end.
