object frmIniTree: TfrmIniTree
  Left = 0
  Top = 0
  Margins.Left = 5
  Margins.Top = 5
  Margins.Right = 5
  Margins.Bottom = 5
  ClientHeight = 1400
  ClientWidth = 2169
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -17
  Font.Name = 'Segoe UI'
  Font.Style = []
  ShowHint = True
  PixelsPerInch = 144
  TextHeight = 23
  object pnlTop: TPanel
    Left = 0
    Top = 0
    Width = 2169
    Height = 48
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 0
    object btnExpand: TButton
      Left = 12
      Top = 6
      Width = 225
      Height = 38
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Action = actExpand
      ImageName = 'Expand'
      Images = imlMain
      TabOrder = 0
    end
    object btnCollapse: TButton
      Left = 246
      Top = 6
      Width = 225
      Height = 38
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Action = actCollapse
      ImageName = 'Collapse'
      Images = imlMain
      TabOrder = 1
    end
    object btnParseDocument: TButton
      Left = 480
      Top = 6
      Width = 225
      Height = 38
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Action = actParseDocument
      ImageName = 'Parse'
      Images = imlMain
      TabOrder = 2
    end
  end
  object pnlMain: TPanel
    Left = 0
    Top = 48
    Width = 2169
    Height = 1352
    Margins.Left = 5
    Margins.Top = 5
    Margins.Right = 5
    Margins.Bottom = 5
    Align = alClient
    BevelOuter = bvNone
    Caption = 'pnlMain'
    TabOrder = 1
    object splVertical: TSplitter
      Left = 722
      Top = 0
      Width = 9
      Height = 1352
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      MinSize = 45
      ResizeStyle = rsLine
    end
    object pnlTree: TPanel
      Left = 0
      Top = 0
      Width = 722
      Height = 1352
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alLeft
      BevelOuter = bvNone
      TabOrder = 0
    end
    object pnlEditor: TPanel
      Left = 731
      Top = 0
      Width = 1438
      Height = 1352
      Margins.Left = 5
      Margins.Top = 5
      Margins.Right = 5
      Margins.Bottom = 5
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 1
      object mmoJson: TMemo
        Left = 0
        Top = 0
        Width = 848
        Height = 1352
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Align = alClient
        BevelInner = bvNone
        BevelOuter = bvNone
        BorderStyle = bsNone
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -17
        Font.Name = 'Consolas'
        Font.Style = []
        Lines.Strings = (
          '[General]'
          'GetRepo=1'
          'FPCOptions='
          'LazarusOptions='
          'FPCRevision='
          'LazarusRevision='
          'FPCBranch='
          'LazarusBranch='
          'SplitFPC=1'
          'SplitLazarus=0'
          'UseWget=0'
          'MakeJobs=1'
          'ExtraVerbose=1'
          'AutoSwitchURL=1'
          'FpcupBootstrappersOnly=0'
          'ForceLocalRepoClient=0'
          'InstallDirectory=D:\development\freepascal\'
          'ConsentWarning=0'
          'CommandFontSize=13'
          'Top=41'
          'Left=2836'
          'Width=1904'
          'Height=998'
          'Maximized=0'
          'GetPackageRepo=0'
          'IncludeHelp=0'
          'SendInfo=1'
          'SystemFPC=0'
          'UpdateOnly=0'
          'UseSoftFloat=1'
          'OnlinePatching=1'
          'Module=17'
          'FPCDebug=0'
          'LazarusDebug=1'
          'Gitlab=1'
          'ApplyLocalChanges=0'
          'fpcVersion=stable.gitlab'
          'lazVersion=stable.gitlab'
          'AskConfirmation=1'
          ''
          '[URL]'
          'fpcURL=https://svn.freepascal.org/svn/fpc/tags/release_3_2_2'
          
            'lazURL=https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_1' +
            '2'
          ''
          '[Patches]'
          'FPCPatches='
          'LazarusPatches='
          ''
          '[ProxySettings]'
          'HTTPProxyURL='
          'HTTPProxyPort=0'
          'HTTPProxyUser='
          'HTTPProxyPass='
          ''
          '[Cross]'
          'IncludeLCL=0'
          ''
          '[i386-windows]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-windows]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i8086-windows]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i386-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch=none'
          ''
          '[aarch64-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[powerpc-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[powerpc64-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[mips-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[mipsel-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i8086-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-android]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch=none'
          ''
          '[aarch64-android]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[mipsel-android]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[jvm-android]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i386-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch=none'
          ''
          '[aarch64-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[powerpc-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[powerpc64-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i8086-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i386-freebsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-freebsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-freebsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch=none'
          ''
          '[i8086-freebsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i386-openbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-openbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-openbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch=none'
          ''
          '[i8086-openbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i386-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch=none'
          ''
          '[powerpc-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[powerpc64-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i8086-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-wince]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch=none'
          ''
          '[i386-iphonesim]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-iphonesim]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i386-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch='
          ''
          '[mipsel-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[avr-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i8086-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[jvm-java]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i386-msdos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-msdos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[arm-msdos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          'CrossARMArch=none'
          ''
          '[i8086-msdos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[i386-haiku]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[x86_64-haiku]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[sparc-windows]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-freebsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-openbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[sparc-msdos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-solaris]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-solaris]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-dragonfly]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-dragonfly]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-dragonfly]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossARMArch=none'
          'Compiler='
          ''
          '[i8086-dragonfly]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-dragonfly]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-netbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-netbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-netbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossARMArch=none'
          'Compiler='
          ''
          '[i8086-netbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-netbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-osNone]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-osNone]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-osNone]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-osNone]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossARMArch='
          'Compiler='
          ''
          '[i8086-osNone]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-osNone]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-osNone]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-win32]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-win32]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-win32]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i8086-win32]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-win32]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-win32]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-win64]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-win64]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-win64]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i8086-win64]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-win64]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-win64]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc64-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv32-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv64-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-darwin]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-freebsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-freebsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-openbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-openbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[riscv32-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[riscv64-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[m68k-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossSubArch='
          'Compiler='
          ''
          '[cpuNone-msdos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-msdos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-dragonfly]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-dragonfly]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-netbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-netbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-aros]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-aros]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-aros]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-aros]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossARMArch=none'
          'Compiler='
          ''
          '[i8086-aros]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-aros]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-aros]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-amiga]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-go32v2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-go32v2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-go32v2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-go32v2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossARMArch=none'
          'Compiler='
          ''
          '[i8086-go32v2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-go32v2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-go32v2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[xtensa-linux]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossARMArch='
          'Compiler='
          ''
          '[i8086-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[xtensa-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[cpuNone-ios]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[i386-ios]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[x86_64-ios]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-ios]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'CrossARMArch=none'
          'Compiler='
          ''
          '[i8086-ios]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[sparc-ios]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[m68k-ios]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[TApplication.Form1]'
          'Form1_WindowState=wsNormal'
          'Form1_Width=1366'
          'Form1_Height=896'
          'Form1_Top=0'
          'Form1_Left=433'
          'Form1_CmdFontSize=8'
          'Form1_CmdFontName=Monospace'
          ''
          '[Form2]'
          'Form2_WindowState=wsNormal'
          'Form2_Width=842'
          'Form2_Height=762'
          'Form2_Top=141'
          'Form2_Left=356'
          ''
          '[aarch64-win64]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-freebsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-openbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-aix]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-embedded-armv4]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CaEABI'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-embedded-armv4t]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CaEABI'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-embedded-armv6]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CaEABI'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-embedded-armv6m]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CaEABI'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-embedded-armv7a]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CaEABI'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-embedded-armv7em]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CfFPV4_SP_D16 -OoFASTMATH -CaEABIHF'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-embedded-armv7m]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CaEABI'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[aarch64-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[mipsel-embedded-pic32mx]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avr1]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avr2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avr25]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avr35]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avr4]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avr5]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avr51]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avr6]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avrtiny]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[avr-embedded-avrxmega3]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv32-embedded-rv32imac]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv32-embedded-rv32ima]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv32-embedded-rv32im]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv32-embedded-rv32i]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv64-embedded-rv64imac]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv64-embedded-rv64ima]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv64-embedded-rv64im]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[riscv64-embedded-rv64i]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[wasm32-embedded]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-msdos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-dragonfly]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-netbsd]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-aros]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-go32v2]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-freertos-armv6m]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CaEABI'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-freertos-armv7em]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CfFPV4_SP_D16 -OoFASTMATH -CaEABIHF'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-freertos-armv7m]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CaEABI'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[aarch64-freertos]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[xtensa-freertos-lx6]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-Cfhard'
          'Compiler='
          ''
          '[xtensa-freertos-lx106]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[aarch64-ios]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[arm-ultibo-armv6]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CfVFPV2 -CIARM -CaEABIHF -OoFASTMATH'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[arm-ultibo-armv7a]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions=-CfVFPV3 -CIARM -CaEABIHF -OoFASTMATH'
          'CrossARMArch=armhf'
          'Compiler='
          ''
          '[aarch64-ultibo]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[wasm32-wasi]'
          'Setting=0'
          'LibPath='
          'BinPath='
          'CrossBuildOptions='
          'Compiler='
          ''
          '[Target]'
          'fpcVersion=stable.gitlab'
          'lazVersion=stable.gitlab')
        ParentFont = False
        TabOrder = 0
        WordWrap = False
      end
      object pnlObjectInspector: TPanel
        Left = 848
        Top = 0
        Width = 590
        Height = 1352
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
      end
    end
  end
  object aclMain: TActionList
    Images = imlMain
    Left = 56
    Top = 112
    object actExpand: TAction
      Caption = '&Expand'
      ImageIndex = 0
      OnExecute = actExpandExecute
    end
    object actCollapse: TAction
      Caption = '&Collapse'
      ImageIndex = 1
      OnExecute = actCollapseExecute
    end
    object actParseDocument: TAction
      Caption = '&Parse document'
      ImageIndex = 2
      OnExecute = actParseDocumentExecute
    end
    object actCopy: TAction
      Caption = 'Copy'
      OnExecute = actCopyExecute
    end
  end
  object ppmTree: TPopupMenu
    Left = 48
    Top = 220
    object mniCopy: TMenuItem
      Action = actCopy
      ShortCut = 16451
    end
  end
  object imcMain: TImageCollection
    Images = <
      item
        Name = 'Expand'
        SourceImages = <
          item
            Image.Data = {
              89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF
              61000001CC4944415478DAA593C94BC25110C74770014114141404FF0737BCE6
              BD88B255A20E1D02B7041151C483882222981B74E85044BB45D45DAFE2F63F08
              82828222082EF0F2370F7FF54B8AA081C77BBC193EEF3BF366788410F88FF116
              807C3E5F1489442B42A110168BCFE7A36F369BC1643261D7783C2ED96C36330B
              C866B3458D46B3A256ABFFF46AABD58266B35972381C66046432196232993841
              DD6E175F638C51A3502838FE72B90C4EA7938780542A458C462327A0DD6E83C5
              62C173A15000954AC5F1572A1570BBDD1490482496009D4E07B6B677F1FCF478
              0F4AA57209E0F57A2920168B1183C100FD7E1FA6D3291BB4B963C5FDF9E186BD
              1308042093C9A05AAD82DFEFA78070384CF47A3DE6BDB177F46B015FEE2EB11E
              B55A0D42A1100504834154D0EBF5607DFFF857C0EBED05C8E5725410894428C0
              E7F3A182E170887FBEB035EB09EE6F37E7EC1DD31B12890415C4E3710AF0783C
              44A7D3715E62EAB17A60C7F3FB750EF3FE6AF57A1D92C92405B85CAE25C06030
              80B5C353AAE0EA0CA452E912209D4E5380DD6E275AAD9613301A8DD87418D962
              B198E36F341A90CBE528201008E01C7C6F969F8C6932661EA2D1A8991DA6F99F
              16E779FF6998E6F528CD7BE77398FE631F3929F5E1B7C392550000000049454E
              44AE426082}
          end>
      end
      item
        Name = 'Collapse'
        SourceImages = <
          item
            Image.Data = {
              89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF
              610000015D4944415478DAA5D3CDAA82401407F01354AE02A11681D03B9885DB
              7C85FB022DEECE3E1042C49016128548107DEDEEC217B8AFA0DBA8F41D04C145
              81D0CA0A26EF0C757792756056C3FCE6CFCC393984107C52B907B0D96C6C8AA2
              5AC562111E2B9FCFE3BDDBED0697CBE5B9E238764451149EC06AB5B26BB55A8B
              6198976E0D82007CDF77BADDAE8081E57289789ECF147DBBDD42AFD7CB61603E
              9FA366B39909D8ED76204912014CD37C0B90659900D3E914351A0D88A208AED7
              6BEAC142A100344DC37EBF07555509A0EB3AE2380E8EC723B4DBED54C0B22CA8
              542A70381C60341A1140D3349CE0743A81F0F59D0AD8BF3F502E977182F1784C
              0045517082F3F98CFF3CADFE7AA3542AE104866110603018A07ABD9EE9115DD7
              85D96C46807EBFFF16B0582C08D0E97410CBB29900CFF360BD5E1360381CE239
              A856AB2F1D0EC310CFC36432119EC394FCA99DF4C14BC394F48193F4CEFF307D
              5277A69FCBE118DB6A430000000049454E44AE426082}
          end>
      end
      item
        Name = 'Parse'
        SourceImages = <
          item
            Image.Data = {
              89504E470D0A1A0A0000000D49484452000000100000001008060000001FF3FF
              61000001B84944415478DA63FCFFFF3F033AD8BEAAA1418B6B7A3D1B8F02032B
              AF220333A73858FCEFF7970CBF3FDF67F8F5E501C39DD75A079C13F73B326233
              E0CE4AC6FF2AE17719B081EFAF4E323CDD1FC5A012FE9F11C4C73060DBCA8606
              73CD17F5C2DA19189ABFBD3AC3F0787F2A837A1444335603AE2D66FCAF15BA1B
              43F3D7D717191E1E2861D08A4568C63060CB8A860633A54BF5629AC1689AAF31
              DC3BD4C6A09B80AA19C380F37318FF1B0676A128F8F2E60EC3F3EB7B80F43D14
              F1A7BF1D0EF8642205E2A6650D0D26923BEAA5D4CD11AA782D80D81C45E3E767
              27196E6C8A6230CD400BC4E35318FF5BFA0431E0039FDEBE66B87AFC3083650E
              5A206E58DCD0602834B75E5E5506A7E60F6F3F315C3A718DC1AE104B20AEEE75
              DC2FFCEF8003B284A0300783A1B92498FDFEED7786F3275F3038951208441858
              B7B0A1419FBBBD5E59859DE1DDBB3F0C674E7E6770ABC4D48CD3806DCD8CFFBD
              BC1818DEBE656038799281C1AB16BB66AC06AC59D0D0A0C7DE582F2CCCC070EC
              2803836F236ECD580DD850C3F8DFC69681E1C86106868016FC9A310C583DAFA1
              81E976633D881DDC4E58338601F39B1DF7F37C39E010DA499C66100000610CD2
              E10FF7C7690000000049454E44AE426082}
          end>
      end>
    Left = 203
    Top = 216
  end
  object imlMain: TVirtualImageList
    AutoFill = True
    DisabledGrayscale = True
    Images = <
      item
        CollectionIndex = 0
        CollectionName = 'Expand'
        Name = 'Expand'
      end
      item
        CollectionIndex = 1
        CollectionName = 'Collapse'
        Name = 'Collapse'
      end
      item
        CollectionIndex = 2
        CollectionName = 'Parse'
        Name = 'Parse'
      end>
    ImageCollection = imcMain
    Width = 24
    Height = 24
    Left = 203
    Top = 108
  end
end
